### ISSUE TITLE
`lxml` trees parsed by `html5lib` can not be used with `lxml.clean`

### ISSUE THREAD

**Issue by tahajahangir** [html5lib/html5lib-python#102]
This simple script fails with html5lib.

```
import html5lib
import lxml.html.clean

parser = html5lib.HTMLParser(tree=html5lib.getTreeBuilder("lxml"), namespaceHTMLElements=False)
# tree = lxml.html.document_fromstring(html)
tree = parser.parse("<html><body><!-- a comment --></body></html>")

cleaner = lxml.html.clean.Cleaner()
cleaner(tree)
```

The problem is `lxml.html.document_fromstring` return an element with type `lxml.html.HtmlElement`, but `HTMLParser.parse` returns with type `lxml.etree._ElementTree`

**Comment by cjerdonek** [comment]
> We unfortunately cannot return a lxml HTML tree unless we entirely break namespace support

Responding to this (and independent of this issue as it was originally filed), would it make sense for `lxml.html` to add support for namespaces?

**Comment by gsnedders** [comment]
> Responding to this (and independent of this issue as it was originally filed), would it make sense for `lxml.html` to add support for namespaces?

Yes, given HTML has been defined, and implemented in browsers, to put things in namespaces for almost ten years now. That might need changes in libxml2 too, though.
