### ISSUE TITLE
<noscript> tags are transformed into html-encoded text via parseRCDataRawtext

### ISSUE THREAD

**Issue by ghost** [html5lib/html5lib-python#104]
Lines 902 and 700 of html5parser.py specify noscript tags should transform into html-encoded text, breaking the output. Judging from the comments it looks intentional—would it be possible to remove this behavior? The noscript tag (AFAIK) is valid in all locations. 

http://www.w3.org/html/wg/drafts/html/master/scripting-1.html#the-noscript-element

Feel free to close this issue if you don't want to change the existing behavior—I can fork and maintain a private version. I am a bit curious as to why it's set as-is, though.

Thanks!

**Comment by Paul424** [comment]
When i place a <link> element inside a <noscript> inside <head> then the contents of the noscript gets encoded: < becomes &lt; After reading the referenced issue i still have no clue how to resolve it? I read about the scripting flag but how/where would i need to do this?
