### ISSUE TITLE
Confusing versioning

### ISSUE THREAD

**Issue by dstufft** [html5lib/html5lib-python#161]
It looks like 0.99 on PyPI is == 1.0b3? However there is also a 0.999 on PyPI which doesn't appear to be equal to anything?

**Comment by gsnedders** [comment]
FWIW, 0.9999 and 1.0b5 are tagged, differing only in version number. (Skipping 1.0b4, given that was effectively 0.999.) Soon to be on PyPI.

**Comment by dstufft** [comment]
Awesome. I'm sure the jython folks will appreciate that.
