### ISSUE TITLE
Wheel packaging format for pypi.org

### ISSUE THREAD

**Issue by stonebig** [html5lib/html5lib-python#165]
Would it be possible to get a .whl universal package on Pypi for your package ?

If I'm right, it's just a matter of adding a setup.cfg file at root level with 
````
[wheel]
universal = 1
````
and then doing this to upload to pypi
````
python setup.py sdist bdist_wheel upload -r pypi
````

**Comment by gsnedders** [comment]
It's not require that simple, given we have different dependencies per Python version. We need to have all the metadata in setup.py instead of in the docs.

**Comment by stonebig** [comment]
Hi,

Ok, so let's wait Python 2.7 being deprecated.

**Comment by gsnedders** [comment]
Oh, we can totally do this. I just need to remember to look up everything that's needed to make sure it works. :)
