### ISSUE TITLE
Update documentation and requirements*.txt after 2.6 ordereddict change

### ISSUE THREAD

**Issue by gsnedders** [html5lib/html5lib-python#179]
As I commented in #177, the changelog (adding a dependency is a pretty major change!), readme (because it's now wrong!), and requirements*.txt files (because they don't require ordereddict on 2.6!) all need updating.

**Comment by gsnedders** [comment]
I'm also unconvinced this is any more "required" than lxml, etc. None of the "core" APIs break without it installed.

**Comment by Ivoz** [comment]
@gsnedders it does manage to ranomly break stuff without notice: https://travis-ci.org/pypa/readme/jobs/80119096
