### ISSUE TITLE
AttributeError raised on invalid data URI in sanitizer

### ISSUE THREAD

**Issue by papachoco** [html5lib/html5lib-python#188]
While trying to sanitize `u'<html><body><audio controls="" src="data:foobar"></audio></body></html>'`

I get an AttributeError exception In HTMLSanitizerMixin line 218

```python
215: m = content_type_rgx.match(uri.path)
216: if not m:
217:      del attrs[attr]
218: if m.group('content_type') not in self.allowed_content_types:
             del attrs[attr]
```

Line 215 returns None , but in line 218 m is assumed to be None

Carlos

**Comment by gsnedders** [comment]
0.99999 now shipped with that running through the sanitizer without it dying now.

**Comment by papachoco** [comment]
Thanks a lot
