### ISSUE TITLE
Relative URLs not allowed by sanitizer after 0.999

### ISSUE THREAD

**Issue by yakky** [html5lib/html5lib-python#189]
This snippet works in 0.999 but not in 0.9999

from html5lib import HTMLParser, sanitizer, serializer, treebuilders, treewalkers

    from html5lib import HTMLParser, sanitizer, serializer, treebuilders, treewalkers

    opts = {}
    opts['tokenizer'] = sanitizer.HTMLSanitizer
    parser = html5lib.HTMLParser(tree=treebuilders.getTreeBuilder("dom"), **opts)

    data = u'Hello World<img src="/static/cms/img/icons/plugins/link.png" alt="Link - A Link" title="Link - A Link" id="plugin_obj_2" />'
    dom_tree = parser.parseFragment(data)
    walker = treewalkers.getTreeWalker("dom")
    stream = walker(dom_tree)
    s = serializer.htmlserializer.HTMLSerializer()
    text = ''.join(s.serialize(stream))

    assert text == data

Issue is not present when not using the sanitiser

**Comment by stefanfoulis** [comment]
in case html5lib causes more problems, we've had good experiences with https://pypi.python.org/pypi/bleach/ .

**Comment by gsnedders** [comment]
Bleach just uses html5lib, FWIW. This should get fixed soonish (and a release should follow), but I'm in the middle of doing stuff like moving flat, so it's all a bit hectic here. It'll just be caused by the data URI changes, if anyone wants to write a PR for this.
