### ISSUE TITLE
support `itemscope` as a boolean attribute

### ISSUE THREAD

**Issue by jvanasco** [html5lib/html5lib-python#194]
`itemscope` should be supported as a boolean attribute.  

for reference, `schema.org` has been pushing it as such (https://schema.org/docs/gs.html#microdata_itemscope_itemtype)

running something through the Tokenizer/Sanitizer will set it to an empty attribute

   input:  `<article itemscope>`
   output:  `<article itemscope="">`

it looks like this can be handled by editing constants.py and doing the following to enable it on all tags:

```
booleanAttributes = {
-    "": frozenset(["irrelevant"]),
+    "": frozenset(["irrelevant", "itemscope"]),
```

**Comment by gsnedders** [comment]
Should probably just check the current list of boolean attributes in the spec, really. We're probably missing others too.

**Comment by willkg** [comment]
I think this bug is fixed now, but if there are still outstanding things in this bug, please add a comment about what still needs to be done.

Thank you for reporting!

**Comment by jvanasco** [comment]
thanks for finding/merging my old PR!
