### ISSUE TITLE
Warning about "Coercing non-XML name" when name contains a column ":"

### ISSUE THREAD

**Issue by JulienPalard** [html5lib/html5lib-python#196]
As: `nonXmlNameBMPRegexp` is defined by `re.compile('[\x00-,/:-@`... (note the column).

[In ihatexml.py, at line 260](https://github.com/html5lib/html5lib-python/blob/master/html5lib/ihatexml.py#L260):
```
replaceChars = set(nonXmlNameBMPRegexp.findall(nameRest))
for char in replaceChars:
    warnings.warn("Coercing non-XML name {}".format(name), DataLossWarning)
```
if a char in a name is in `nonXmlNameBMPRegexp`, like `:`, a Warning is triggered, yet, as far as I searched, `:` is allowed for namespace purpose and by definition in the [XML 1.1 spec](http://www.w3.org/TR/xml11/):

> [Definition: A Name is a token beginning with a letter or one of a few punctuation characters, and
> continuing with letters, digits, hyphens, underscores, colons, or full stops, together known as name
> characters.] Names beginning with the string "xml", or with any string which would match (('X'|'x')
> ('M'|'m') ('L'|'l')), are reserved for standardization in this or future versions of this specification.

Did I missed something obvious here or is this a bug ?

**Comment by gsnedders** [comment]
> Did I missed something obvious here or is this a bug ?

Yes, you're not looking at the [Namespaces in XML](http://www.w3.org/TR/xml-names/) spec, which places far stricter rules on names with colons in them. Almost all XML implementations implement XML *with* Namespaces in XML, and hence one is bound by the stricter rules the latter places on colons.

Also, FWIW, XML 1.1 is mostly abandoned and only really of historical interest. XML 1.0 5th Edition mostly makes it obsolete (for better or for worse, given the changes in 5th ed…), and XML 1.0 4th Edition or XML 1.0 5th Edition are what almost everyone implements (yes, they differ normatively!) — 1.1 never saw such widespread deployment.

**Comment by gsnedders** [comment]
(If that doesn't make sense to you, let me know and I'll try and explain better.)

**Comment by JulienPalard** [comment]
Hum, I'm not an XML guy (i hate it too) but I'm trying to understand it right, from
[Extensible Markup Language (XML) 1.0 (Fifth Edition)](http://www.w3.org/TR/2008/REC-xml-20081126/) I read:
> Note:
> 
> The Namespaces in XML Recommendation [XML Names] assigns a meaning to names containing colon characters. Therefore, authors should not use the colon in XML names except for namespace purposes, but XML processors must accept the colon as a name character.

It seems explicit here that ":" is allowed.

I changed the warning to:

```
    warnings.warn("Coercing non-XML name {}".format(name), DataLossWarning)
```

Just to have an idea of what's going wrong (in a real world, we better use a kind of `binascii.hexlify`, because if the name is wrong, control character are probably in it, but that's just to get an idea, not to propose a patch). And I'm getting:

 - Coercing non-XML name xmlns:fb
 - Coercing non-XML name xml:lang
 - Coercing non-XML name xmlns:og
 - Coercing non-XML name fb:like

The namespaces seems declared:

```
<!doctype html><html id="default" xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml"  ...
```

Yet I'm not an XML-oriented-guy so I can miss something big here, but if the problem is that my namespace is not declared the right way, the ticket still probably worth it: We should probably try to display "Undeclared namespace fb" instead of "Coercing non-XML name" ?

**Comment by gsnedders** [comment]
> It seems explicit here that ":" is allowed.

Well, yes… Most don't, however. :) lxml gives: `XMLSyntaxError: Namespace prefix foo on bar is not defined, line 1, column 9`, for example.

> The namespaces seems declared

HTML doesn't have any sort of namespace declaration — "xmlns:fb" is just another attribute to HTML; in XML that'd be a `fb` attribute in the `http://www.w3.org/2000/xmlns/` namespace, in HTML it's a "xmlns:fb" attribute in the void namespace. Because HTML doesn't have anything in way of namespaces, it doesn't make sense to have "undeclared namespace" errors.

**Comment by JulienPalard** [comment]
Just to disambiguate, are we parsing XML blindly at this stage or do we know we're parsing HTML ? Because if we're aware we're parsing HTML we should probably allow colon in names:

[HTML 5 2.9 Namespaces](http://www.w3.org/TR/2011/WD-html5-20110405/namespaces.html):
> In the HTML syntax, namespace prefixes and namespace declarations do not have the same effect as in XML. For instance, the colon has no special meaning in HTML element names.

"the colon has no spacial meaning" at least mean "colon is allowed" ?

**Comment by gsnedders** [comment]
> Just to disambiguate, are we parsing XML blindly at this stage or do we know we're parsing HTML ? Because if we're aware we're parsing HTML we should probably allow colon in names:

We're parsing HTML into a data-structure designed to contain XML, and many of those data-structures (those for which ihatexml is used) require that element names, etc., are acceptable names in XML. What we do more-or-less follows [§ 12.2.7 Coercing an HTML DOM into an infoset](https://html.spec.whatwg.org/multipage/syntax.html#coercing-an-html-dom-into-an-infoset).

> "the colon has no spacial meaning" at least mean "colon is allowed" ?

Basically, yes.
