### ISSUE TITLE
Bug in the ElementTree append?

### ISSUE THREAD

**Issue by iherman** [html5lib/html5lib-python#207]
Consider the following code:

```
import html5lib
import xml.etree.ElementTree as ET

example_XML="""<?xml version="1.0"?>
<data>
    <country name="Liechtenstein">
    </country>
 </data>
"""

example_HTML="""<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
    </body>
</html>
"""

tree = html5lib.parse(example_HTML, namespaceHTMLElements=False)
# tree = ET.fromstring(example_XML)
q = ET.Element('rubbish')
tree.append(q)
```

Running the code as is leads to:

```
Traceback (most recent call last):
  File "/Users/ivan/Desktop/test.py", line 23, in <module>
    tree.append(q)
TypeError: must be Element, not Element
```

Running the code switching off the ``html5lib`` implementation in favor of XML parsing, ie, 

```
# tree = html5lib.parse(example_HTML)
tree = ET.fromstring(example_XML)
```

works. This smells like a bug:-(

**Comment by gsnedders** [comment]
This isn't a bug. This is a result of the terrible inconsistency in the ElementTree API about whether an `Element` gets returned or an `ElementTree` after parsing. We return an `ElementTree`, which has a single root element and one cannot append to it. `etree.fromstring` returns an `Element` which is just a normal element (and `etree.parse` returns an `ElementTree`, to prove it isn't consistent).

See `ElementTree.getroot()` to get the root `Element` of a tree.
