### ISSUE TITLE
Default encoding has changed from "utf-8" to "windows-1252" between old and recent version

### ISSUE THREAD

**Issue by lsamper** [html5lib/html5lib-python#215]
When chardet and charade are not installed, detectEncoding method falls back to 
html5lib.inputstream.HTMLInputStream.defaultEncoding  
and this is set to "windows-1252" ("iso-8859-1").
line 429 in inputstream.py:
    self.defaultEncoding = "windows-1252"
https://github.com/html5lib/html5lib-python/blob/92ed92a0a3166bf022fa48ba46b1c66f4f223d4b/html5lib/inputstream.py#L429

Actually, this was not the case in an old html5lib version. 
I wonder why have you make this choice? Is it a bug?
Default encoding shouldn't be "utf-8" in html5?
http://www.w3schools.com/html/html_charset.asp

Thank you

**Comment by gsnedders** [comment]
The default encoding for HTML is never utf-8. That w3schools page is entirely wrong.

In principle the default encoding is locale dependant, with most locales using windows-1252. We just use windows-1252 rather than involving locale-dependant behaviour.

I'm unaware of html5lib having ever changed behaviour: looking quickly even in 2010 we had this behaviour.

**Comment by lsamper** [comment]
Ok, thank you for your reply. 
Actually my html document is correct, but the information about encoding is not in the first 512 bytes but in the 1024 first ones.

The time to parse my document raises from 62ms to 430ms when chardet is invoked. Thus I will patch the lib in order to increase the number of bytes read to check for encoding declaration in metas:
html5lib.inputstream.HTMLBinaryInputStream.numBytesMeta (from 512 to 1024).

This is the beginning of my html file:
```html
<!DOCTYPE html>
<!--[if IEMobile 7]><html class="iem7"  lang="fr" dir="ltr"><![endif]-->
<!--[if lte IE 6]><html class="lt-ie9 lt-ie8 lt-ie7"  lang="fr" dir="ltr"><![endif]-->
<!--[if (IE 7)&(!IEMobile)]><html class="lt-ie9 lt-ie8"  lang="fr" dir="ltr"><![endif]-->
<!--[if IE 8]><html class="lt-ie9"  lang="fr" dir="ltr"><![endif]-->
<!--[if (gte IE 9)|(gt IEMobile 7)]><!--><html  lang="fr" dir="ltr" prefix="content: http://purl.org/rss/1.0/modules/content/ dc: http://purl.org/dc/terms/ foaf: http://xmlns.com/foaf/0.1/ og: http://ogp.me/ns# rdfs: http://www.w3.org/2000/01/rdf-schema# sioc: http://rdfs.org/sioc/ns# sioct: http://rdfs.org/sioc/types# skos: http://www.w3.org/2004/02/skos/core# xsd: http://www.w3.org/2001/XMLSchema#"><!--<![endif]-->

<head>
  <meta charset="utf-8" />
<meta name="content-type" content="article" />
```
