### ISSUE TITLE
Wrong HTML comments cause ValueError in lxml

### ISSUE THREAD

**Issue by neumond** [html5lib/html5lib-python#225]
I've got exception here https://github.com/lxml/lxml/blob/master/src/lxml/lxml.etree.pyx#L3017
lxml explicitly disallows bad comment tag contents, while html5lib handles them and passes over. While I don't really care about comment content, I can't proceed working with DOM due to exception even when I set strict=False. It is still unclear for me which library should be responsive for that, but from my point of view it should be done like fix_content_errors=True key argument passed to html5lib's parse.

**Comment by gsnedders** [comment]
Dupe of #214.
