### ISSUE TITLE
Use Semantic Version Numbering

### ISSUE THREAD

**Issue by jpotterm** [html5lib/html5lib-python#242]
Please follow the [semantic versioning](http://semver.org/) standard when tagging releases. At the very least, this would mean:

1. Always have three numbers in the version e.g. 0.9.0
2. The successor to 0.9.0 should be 0.10.0 not 0.99.0

This would make it much easier for packages depending on html5lib-python to specify dependencies. I think version 1.0.0 is a great time to make the switch.

**Comment by gsnedders** [comment]
We do. :)

See point four:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

**Comment by jpotterm** [comment]
I disagree. When it says "Anything may change at any time" that doesn't include the version number.

> A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers, and MUST NOT contain leading zeroes. X is the major version, Y is the minor version, and Z is the patch version. Each element MUST increase numerically. For instance: 1.9.0 -> 1.10.0 -> 1.11.0.

If I'm not explaining it clearly, let me know; I'd be happy to elaborate.

If you're intentionally ignoring semantic versioning that's fine, you can do what you want with your own packages.

**Comment by gsnedders** [comment]
Hmm, I can see that argument. I think we're unlikely to change our pre-1.0.0 numbering scheme now given we're relatively close (something I've been saying for far too long), given I don't think it's worth changing. (Ultimately you still have no guarantee of API stability anyway, which makes the numbering scheme not very important pre 1.0.0, IMO. Feel free to say if you disagree!)

**Comment by jpotterm** [comment]
Yeah I agree it can be awkward to change it now, so I think 1.0.0 is a great opportunity to start doing things the new way. And by the way, thanks for your work on this great package!
