### ISSUE TITLE
Update CONTRIBUTING guidelines on CHANGES

### ISSUE THREAD

**Issue by gsnedders** [html5lib/html5lib-python#268]

**Comment by sedrubal** [comment]
Does this include to update readthedocs? Because readthedocs documentation is outdated...

**Comment by willkg** [comment]
This is in `CONTRIBUTING.rst` currently:

```
- **Add a changelog entry** at the top of ``CHANGES.rst`` following
  existing entries' styles.
```

@gsnedders Is there anything else to do in this issue?

**Comment by gsnedders** [comment]
IIRC the vague unwritten policy had been to have end-user significant changes in CHANGES rather than everything, though maybe it's just too hard to judge significance.

**Comment by willkg** [comment]
Ok. I think that's a maintainer-job and not something we want to push on contributors unless we can figure out a way to explain it such that they're likely to succeed.

Given that, I'm going to close this out.
