### ISSUE TITLE
Kill Landscape

### ISSUE THREAD

**Issue by gsnedders** [html5lib/html5lib-python#273]
A lot of PRs fail to report a result back because of Landscape. Let's just replace it with running a fixed version of pylint on Travis/tox.

**Comment by willkg** [comment]
@gsnedders I don't see "Landscape" in this project. Can you explain this issue more?

**Comment by gsnedders** [comment]
It was a code analysis tool, http://landscape.io, except far too noisy and random. We should just have what we care enabled in Travis CI. I've disabled it now.
