### ISSUE TITLE
 cannot import name 'sanitizer'

### ISSUE THREAD

**Issue by erikzenker** [html5lib/html5lib-python#277]
I want install the django cms which uses the sanitizer of the html5lib,
but I get the error shown above in the title.

when I just import the sanitizer from html5lib:
``` python
from html5lib import sanitizer
```
I get the following error:

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from html5lib import sanitizer
ImportError: cannot import name 'sanitizer'
```
I installed html5lib from pip:

``` bash
pip install html5lib
```
Is the sanitizer module not available anymore ?

**Comment by stefanfoulis** [comment]
@erikzenker It looks like it has been removed (or moved). Quickfix is to use a slightly older version of the package where sanitizer is still there:

```
pip install html5lib<0.99999999
```

ot: what is it with those weird version numbers anyway? You know you could also make it 0.10 .

**Comment by gsnedders** [comment]
That's #72 and #110. The sanitizer now exists only as a filter for the treewalkers, rather than something touching the tokenizer in odd ways that was likely broken.

Our state of terrible documentation probably doesn't help here, and the changelog entry is rather useless in hindsight. The common-case is something like:

```
from html5lib import parse, serialize

def clean(s):
    d = parse(s)
    return serialize(s, sanitize=True)
```

(0.10 is less than 0.9999999, so no, that option's long gone.)

**Comment by macolo** [comment]
You could make it 1.0 though. Counting the 9s makes me dizzy.

**Comment by DanielTate** [comment]
This is still not working.... Are there any real solutions to this?

**Comment by erccarls** [comment]
Any luck here?

**Comment by vhquang** [comment]
As a2917e9, `sanitizer` is moved into `filter. So to import (as of version 1.1), you would do:
```python
from html5lib.filters import sanitizer
```
