### ISSUE TITLE
Incorrect call of HTMLUnicodeInputStream in _inputstream.py

### ISSUE THREAD

**Issue by marazt** [html5lib/html5lib-python#281]
Hi, while using Weasyprint 0.29 (that uses html5lib 0.999999999) for printing templates, I have found following issue:

`env/local/lib/python2.7/site-packages/html5lib/_inputstream.py", line 149, in HTMLInputStream
    return HTMLUnicodeInputStream(source, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'encoding'`

It seems that it is caused by changes in issue #120 (line 149). **HTMLUnicodeInputStream** constructor is called with multiple arguments, but the constructor itself has only one parameter.

Edit: version **0.9999999** (7x9) is working correctly.

**Comment by gsnedders** [comment]
This is https://github.com/Kozea/WeasyPrint/issues/334.
