### ISSUE TITLE
Add an error for invalid children of <ul>

### ISSUE THREAD

**Issue by jdufresne** [html5lib/html5lib-python#283]
```
>>> import html5lib
>>> parser = html5lib.HTMLParser()
>>> parser.parseFragment('<ul><ul><li>item</li></ul></ul>')
>>> print(parser.errors)
[]
```

I would expect an error like: "Element ul not allowed as child of element ul in this context." This is the error reported by [W3.org's validator](https://validator.w3.org/nu/#textarea).

The [spec states](https://www.w3.org/TR/html5/grouping-content.html#the-ul-element) only `<li>` tags are valid children of `<ul>`.

**Comment by gsnedders** [comment]
We don't implement a validator, and as such we don't implement the content model constraints. The parser only reports parse errors, which are explicitly called out in the [Parsing HTML documents](https://html.spec.whatwg.org/multipage/syntax.html#parsing) section. A quick skim makes it look like that shouldn't produce any parse errors. Implementing an actual validator is a large project to undertake, and really something out of scope here.

**Comment by jdufresne** [comment]
Ah, I see. Thanks for the response.
