### ISSUE TITLE
Sanitizer example in documentation needs rewriting

### ISSUE THREAD

**Issue by malcolmr** [html5lib/html5lib-python#289]
After #72, the example in the documentation at https://html5lib.readthedocs.io/en/latest/movingparts.html#tokenizers is no longer valid (see also #277).

(Also the links to `tokenizer.py` and `sanitizer.py` are both 404.)

**Comment by willkg** [comment]
This was fixed at some point, but I'm not sure offhand when. The example in the latest docs is correct now. Closing this out.

Thank you for reporting!
