### ISSUE TITLE
flake8 v3 does not support Python 2.6

### ISSUE THREAD

**Issue by jayvdb** [html5lib/html5lib-python#290]
flake8 v2 supported Python 2.6, and is used by the Travis builds.

flake8 v3 has come out of beta, though is full of bugs, but more importantly it comes with a clear intent to not support Python 2.6, which is the trendy thing to do.
https://gitlab.com/pycqa/flake8/commit/cde783d135953d7d16a1373f13b066731083e477
https://gitlab.com/pycqa/flake8/commit/c8ad626525631314decbb5bd544be47102610fd0

To support continued linting of Python 2.6, raise upstream and/or pin flake8<3 at least on Python 2.6

Or drop support for Python 2.6.  Is that an option?  If not, it would be good to clearly explain why Python 2.6 support is needed, here and upstream.

**Comment by gsnedders** [comment]
We need Python 2.6 support because otherwise `pip` needs to fork html5lib, which I'm keen not to have happen! We'll drop 2.6 support when pip does, basically.

**Comment by jdufresne** [comment]
Pip issue to drop Python 2.6 <https://github.com/pypa/pip/issues/3955>
