### ISSUE TITLE
PLZ Move public api back

### ISSUE THREAD

**Issue by Krukov** [html5lib/html5lib-python#295]
It is very dangerous to make changes that breaks down other libraries! :suspect: 
I taking about https://github.com/html5lib/html5lib-python/commit/c4dd6771836841ee796af8035dbf8239074ed5ec

(take a look at this https://github.com/xhtml2pdf/xhtml2pdf/blob/0.1b2/xhtml2pdf/parser.py#L17)

Please revert this and other related commits that changes names of public interfaces
You can use `warnings` library to notify users about `deprecated` modules/classes/methods.

**Comment by willkg** [comment]
It's been over a year now. I don't think we're going to undo this, so I'm going to close this out.

I'm sorry this affected you and other projects and was difficult to deal with.
