### ISSUE TITLE
accept python-distribute-0.6.49

### ISSUE THREAD

**Issue by mcirsta** [html5lib/html5lib-python#296]
There is a check for : 

html5lib requires setuptools version 18.5 or above; please upgrade before installing (you have 0.6)

 I have python-distribute-0.6.49 and when removing that check everything seems to work fine.

**Comment by jayvdb** [comment]
This has probably been fixed by #285, unless it introduced new dependencies not in python-distribute 0.6 .
Could you test ; if it fails I'd be keen to see the error and then would try to find a workaround for you.

**Comment by mdxs** [comment]
By silence procedure, I would say this can be closed now; as @mcirsta didn't report back and @jayvdb thinks that #285 resolved this issue.

**Comment by willkg** [comment]
@mdxs Thank you! Closing this out.
