### ISSUE TITLE
Non-standard tags in header move remaining tags to body

### ISSUE THREAD

**Issue by johnlb** [html5lib/html5lib-python#304]
In particular, this html:

```
<html>
<head>
	<tech value="generic">
	<link rel="stylesheet">
</head>
<body>
	<div> some div text </div>
</body>
</html>
```

becomes this (after parsing):
```
<html>
<head>
</head>
<body>
	<tech value="generic">
		<link rel="stylesheet">
		<div> some div text </div>
	</tech>
</body>
</html>

```

Also note that if I put ``link`` above ``tech``, ``link`` stays in the correct position, but ``tech`` behaves the same.

**Comment by johnlb** [comment]
PS - closing ``tech`` keeps it from wrapping everything in the body (that is probably unsurprising), but it still moves everything after it into the body.

**Comment by gsnedders** [comment]
This behaviour is consistent with what the HTML standard says and what all browsers implement.
