### ISSUE TITLE
serialize() makes a mailto href attribute unusable if it contains a query with ampersands 

### ISSUE THREAD

**Issue by lmende** [html5lib/html5lib-python#310]
`serializer.htmlserializer.serialize()` (line:248) replaces the desired `&` with `&amp;` so that the given mailto - href is broken afterwards, see below:
```
In [1]: import bleach
In [2]: bleach.clean('<a href="mailto:et@far.away?subject=Hi&body=please%20call">send</a>')
Out[2]: '<a href="mailto:et@far.away?subject=Hi&amp;body=please%20call">send</a>'
```

The resulting serialized url isn't recognized by standard mail programs like _thunderbird_ or _apple mail_.

**Comment by gsnedders** [comment]
`'<a href="mailto:et@far.away?subject=Hi&amp;body=please%20call">send</a>'` and `'<a href="mailto:et@far.away?subject=Hi&body=please%20call">send</a>'` are semantically equivalent, so it should work, as both represent the same URL, `mailto:et@far.away?subject=Hi&body=please%20call`.

Where are you using the URL such that it doesn't work with them? Certainly trying it with a data URL (`data:text/html,<a%20href="mailto:et@far.away?subject=Hi&amp;body=please%20call">send</a>`) and then clicking on send works fine with both Thunderbird and Mail.app here.

**Comment by lmende** [comment]
You can paste 
```
mailto:et@far.away?subject=Hi&amp;body=please%20call
```
into any browser and the mail program opens without the body.
If you paste:
```
mailto:et@far.away?subject=Hi&body=please%20call
```
instead, subject and body will be fine.

**Comment by gsnedders** [comment]
Why are you copying it straight from the HTML source? This seems like a very unusual use-case! If you copy the link from the browser, it works fine; if you copy the link from a parse tree, it works fine.

**Comment by zcorpan** [comment]
@Imende your problem is exactly equivalent to complaining about a JSON serializer that it backslash-escapes quote characters in a string, and then try to use the escaped string in a non-JSON context.

**Comment by lmende** [comment]
@zcorpan that is a good point, may be I'm not fully aware of what the html5.serializer is for. I use bleach (and bleach uses the serializer) to clean up thousands of data sets with a html description, which comes from a tinymce user input or from an unknown source. 
This cleansing is the preparation to use those descriptions on a web page where now the mailto - links are broken!

**Comment by zcorpan** [comment]
If the final output in the web page's source is

```html
<a href="mailto:et@far.away?subject=Hi&amp;body=please%20call">send</a>
```

then it is correct. If you click the link, the URL will be `mailto:et@far.away?subject=Hi&body=please%20call` because the HTML parser changes `&amp;` into `&`.

Compare with `bleach.clean('foo < bar')` -> `foo &lt; bar`.

**Comment by lmende** [comment]
You both were right - sorry - if the output is shown via web page source the browser handles the link correctly. The only problem was, that I pasted that link into the browsers address bar for testing purpose. In this case it was mis-interpreted, but that is no common use case.
