### ISSUE TITLE
sanitize filter introduced in 0.99999999 (8 9s) creates extra tags

### ISSUE THREAD

**Issue by willkg** [html5lib/html5lib-python#312]
I'm the maintainer for bleach. I've spent a good portion of the last few days trying to rewrite bleach to work with html5lib >= 0.99999999 (8 9s). It's been interesting.

The sanitizer that we used in 0.9999999 (7 9s) is gone. That's replaced with a filter system. So previously, bleach would "tap into" the pipeline with a Tokenizer, but now it's "tapping into" the pipeline with a Filter.

The problem I'm having is that we're getting different output. For example with this string:

```
Yeah, sure. <sarcasm/>
```

With html5lib 0.9999999 (7 9s), we get `Yeah, sure. &lt;sarcasm/&gt;`.

With html5lib 0.99999999 (8 9s), we get `Yeah, sure. &lt;sarcasm&gt;&lt;/sarcasm&gt;`.

I took bleach out of the equation and just used the regular sanitization stuff in html5lib and wrote these two test scripts:

html5lib 0.9999999 (7 9s):

```
#!/usr/bin/env python

import html5lib
from html5lib import sanitizer
from html5lib.serializer.htmlserializer import HTMLSerializer


def sanitize(text):
    p = html5lib.HTMLParser(tokenizer=sanitizer.HTMLSanitizer)
    walker = html5lib.treewalkers.getTreeWalker('etree')
    domtree = p.parseFragment(text)

    stream = walker(domtree)
    serializer = HTMLSerializer()
    return serializer.render(stream)


print(sanitize('Yeah <sarcasm/>'))
```

html5lib 0.99999999 (8 9s):

```
#!/usr/bin/env python

import html5lib
from html5lib.filters import sanitizer
from html5lib.serializer import HTMLSerializer


def sanitize(text):
    dom = html5lib.parseFragment(text, treebuilder="etree")
    walker = html5lib.getTreeWalker("etree")
    stream = walker(dom)

    s = HTMLSerializer()

    return s.render(sanitizer.Filter(stream))


print(sanitize('Yeah <sarcasm/>'))
```

I think what's going on is that in 0.9999999 (7 9s), sanitizing via tokenizer kicks in *before* the etree tree walking. The sanitizing converts the `<sarcasm/>` (a disallowed tag) into escaped text data. Thus it doesn't get an end tag.

In 0.99999999 (8 9s), sanitizing via filter kicks in *after* the etree tree walking which creates the end tag, then both the start and end tags get escaped.

Am I right or am I missing something?

If I'm right, any ideas how to deal with this in bleach? Seems like a showstopper.

**Comment by willkg** [comment]
As a side note, I'm super tired. If I'm horribly wrong about any of the bits above, I really apologize.

**Comment by gsnedders** [comment]
To some degree, there was always weird mangling with bogus tags, it's just got weirder now. `'<foo\tbar>` always became `&gt;foo bar>` (I think? it might've been `&gt;foo bar="">`? I realise I'm talking about detail, but I too am pretty tired so might screw up on the detail. :))

I guess there's a bunch of related questions here, all related to what is acceptable output:

* `<p>foo<p>bar`
* `<p>foo<table><tbody><tr><td>xxx</td></tr></tbody></table>`
* `<script>alert(1)</script>`
* `this is a <script> test`
* `<this is a bogus test>`
* `<sarcasm>obviously</sarcasm>`
* `well, that's some </sarcasm>`
* `<sarcasm>yes, definitely a feature`

From memory, there was also some discussion before about dropping unknown tags and sometimes their content, such that `<x>y</x>` would become `y` and `<script>y</script>` would become an empty string, and I seem to remember that being seen to be desirable for Bleach. I want to say that got implemented, but I could of course be simply misremembering (I haven't checked!).

**Comment by willkg** [comment]
Bleach can drop disallowed tags (it's more than just unknown tags--it's all not-allowed tags) or it can escape them. So it can do `<x>y</x>` -> `y` as well as `<x>y</x>` -> `&lt;x&gt;y&lt;/x&gt;`.

`<sarcasm/>` is an interesting input. I've seen it and similar things pop up occasionally. Bleach has always had issues with various categories of input, some of which I'd like to fix at some point. 

I have fears that it's indicative that there are other issues, too, since the pipeline will now be treating everything as if it were HTML and changing it rather than just HTML tags. I haven't finished the rewrite and there are still a lot of failing tests, but this was the first big issue I bumped into. My other fear is that the new architecture causes Bleach to take a step backwards rather than a step forwards and that it's now impossible to fix those things because the integral parts are inaccessible.

Seems like my theory on what's happening is either right on or really close.

What're our options? Should I subclass HTMLParser and override `_parse` so I can do sanitizing at the tokenizing step? Should I write my own treebuilder that deals with disallowed tags at that stage somehow? Maybe subclass HTMLParser and override `normalizeToken`?

**Comment by gsnedders** [comment]
> Seems like my theory on what's happening is either right on or really close.

Oh, yeah, it is, entirely. Sorry, I should've been explicit about that.

The proper solution, I suspect, is to have a tree such that you can access the original strings each token was parsed from. We're quite obviously a long way away from that. Blargh. I thought we could get away with just dropping disallowed tags everywhere which makes this not a problem; the escaping case is harder. (And in reality, I guess the right solution might be to escape some, like `sarcasm`, and drop others, though maybe that's too magical.)

The correct solution is probably making sure there's an API in the next release that works for you. I'm still a bit worried about various hypothetical attack vectors from using the tokenizer and changing those tokens, but maybe I need to sit down with model of the parser and convince myself those aren't attack vectors (they might not be). What I *really* don't want to allow is arbitrary mutation of the token stream, because that does open up all kinds of bizarre attack vectors.

**Comment by willkg** [comment]
I'll spend some more time understanding treewalkers and the other parts involved. I only picked up Bleach maintenance a year ago, so this is all still new-ish to me and I don't have a good mental model of the bits, yet.

I'll also finish up redoing Bleach to use the sanitize Filter and see what else pops up.

**Comment by gsnedders** [comment]
@willkg Okay, here's a bunch of fairly off-hand thoughts:

* A very limited tokenizer API may well be the right level to do this at (though it does have its downsides, especially when it comes to more awkward HTML: `<svg><title>` does what? simply stripping all title tokens isn't really a great thing to do from an accessibility point-of-view!). I'm thinking of something like a function that takes a token and returns a list of tokens, essentially intercepting them along their way to the tree construction stage… and probably doing some lightweight validation that you aren't doing something crazy that'll break everything!
* I'm not entirely sure I want to be maintaining the sanitizer, and maybe it makes sense to simply push more of the code into bleach (it is, presently, entirely using public APIs; I'm also not at all paid to work on this and it frequently shows in terms of how much I'm around, which isn't great if there are security bugs).
* Feel free to file documentation bugs, especially when it comes to high-level stuff as to how everything fits together. I'm probably not the best person to write it, given I've been vaguely involved for nine-ish years.
* Maybe the right way to work out what level it should operate at is to sit down with a whole load of random inputs and figure out what we want as output.

**Comment by willkg** [comment]
I've had this problem with github where I wasn't getting notification emails for like the last year. (Hopefully fixed now.) So I completely missed this last reply. Sorry about that.

A tokenizer option seems plausible. I started looking into re-implementing the tokenizer-based sanitizer that html5lib 0.9999999 (7 9s) had, but I got stuck on figuring out a good way to specify the tokenizer without overriding `HTMLParser._parse`. I haven't thought about that much since then.

I totally get you on not wanting to maintain the sanitizer and the difficulties of working on this in your free time. I'm doing most of bleach maintenance in my free time, too. (And some other projects.) If I had my druthers, whatever system we work out would have minimal maintenance effort for you and me.

My next step is finishing up a first pass on the Bleach reimplementation using html5lib 0.99999999 (8 9s). I got a lot further since my last comment, but I think I'm missing some bits still. After that, I'll have a list of tests that continue to work and tests that have regressed. We could base a list of inputs and expected output on that.

**Comment by willkg** [comment]
I think I'm mostly done with a Bleach rewrite with html5lib >= 0.99999999 (8 9s) and have a much clearer understanding of this issue as it relates to Bleach. My fears were for naught--the only big regression is this one--it creates extra tags. That manifests itself in a few different kinds of strings all of which are malicious anyhow, so I don't think they matter.

The only case which isn't malicious in our test suite is in the `</sarcasm>` case.

Given that, I don't think this is as big a deal as I feared and I'm going to forge ahead. If users write up bug reports with other cases, I can look into it then. Our conversation has given me some options to investigate should the need arise.

Given that, I'm going to close this out.

Thank you for your help!
