### ISSUE TITLE
Links to tokenizer.py and sanitizer.py broken

### ISSUE THREAD

**Issue by Ryuno-Ki** [html5lib/html5lib-python#313]
As already mentioned in #289 the links to tokenizer.py and sanitizer.py are broken in https://github.com/html5lib/html5lib-python/blob/1a28d721091a2c433c6e8471d14cbb75afd70d1c/doc/movingparts.rst#htmltokenizer

Instead of `<https://github.com/html5lib/html5lib-python/blob/master/html5lib/tokenizer.py>` and `<https://github.com/html5lib/html5lib-python/blob/master/html5lib/sanitizer.py>` they should point to https://github.com/html5lib/html5lib-python/blob/master/html5lib/_tokenizer.py and https://github.com/html5lib/html5lib-python/blob/master/html5lib/filters/sanitizer.py respectively.

Caused by https://github.com/html5lib/html5lib-python/commit/c4dd6771836841ee796af8035dbf8239074ed5ec and https://github.com/html5lib/html5lib-python/commit/a2917e950df0a06b0c46c3ac7f84c3c797af0e43

**Comment by willkg** [comment]
This was fixed in #332, so we're all set here. Thank you for reporting!
