### ISSUE TITLE
pip install fails with AttributeError: 'NoneType' object has no attribute 'splitlines'

### ISSUE THREAD

**Issue by SamuelMarks** [html5lib/html5lib-python#315]
The issue is that `dist = html5lib 1.0b10` and `metadata = None`. `metadata` should equal an object with a `splitlines` method.

Usually it's your README.

**Comment by gsnedders** [comment]
Where is `metadata`?

What are you doing such that `pip install` fails? With pip 9.0.1, I can install html5lib fine.

**Comment by willkg** [comment]
@SamuelMarks Can you show an example of your issue with what you're typing and what gets printed to stdout/stderr?

**Comment by willkg** [comment]
I don't know how to reproduce this and the author isn't replying, so I'm going to close this out. If it's an issue other people are hitting, someone will comment and/or write up a new one.
