### ISSUE TITLE
Unexpected handling of nested <a> tags

### ISSUE THREAD

**Issue by akxlr** [html5lib/html5lib-python#326]
I am using html5lib to parse some invalid HTML containing nested `<a>` tags. I apologise if the below is expected behaviour (I am aware nested `<a>` tags are not allowed).

```
Python 2.7.12 (default, Sep 28 2016, 18:41:32)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from lxml import etree
>>> import html5lib
>>> etree.tostring(html5lib.parse('<div><div>Body</div></div>', treebuilder='lxml', namespaceHTMLElements=False))
'<html><head/><body><div><div>Body</div></div></body></html>'
>>> etree.tostring(html5lib.parse('<a href="link1"><a href="link2">Body</a></a>', treebuilder='lxml', namespaceHTMLElements=False))
'<html><head/><body><a href="link1"/><a href="link2">Body</a></body></html>'
```

Note the self-closing tag in the second example. I would instead expect

```
'<html><head/><body><a href="link1"><a href="link2">Body</a></a></body></html>'
```

If this is indeed the expected behaviour, is there some way I go about parsing nested `<a>` tags to get the latter result?

**Comment by gsnedders** [comment]
This is the expected behaviour per spec (and it does indeed match what all browsers do in this case). We don't offer any way to deviate from the spec-compliant behaviour.
