### ISSUE TITLE
Release to pypi

### ISSUE THREAD

**Issue by davidread** [html5lib/html5lib-python#328]
It would be helpful if you are able to release another version to pypi. The current latest dates from July 2016.

Personally I could do with this fix:
https://github.com/html5lib/html5lib-python/pull/301
coming through into my CI.

**Comment by gsnedders** [comment]
With a huge thanks to @willkg for making everything happen, 1.0 is now on PyPI.

**Comment by hugovk** [comment]
The 1.0 milestone may be closed now: 

* https://github.com/html5lib/html5lib-python/milestone/1
