### ISSUE TITLE
Drop Python 2.6 support

### ISSUE THREAD

**Issue by gsnedders** [html5lib/html5lib-python#330]
See also #309. Now that https://github.com/pypa/pip/pull/4343 has landed, we can probably start thinking again about dropping 2.6 support. As mentioned in #309, we probably want to wait until pip 10.0 actually ships, however.

**Comment by hugovk** [comment]
Here's the pip installs from PyPI for the last month:
```
$ pypinfo --percent --pip html5lib pyversion
python_version percent download_count
-------------- ------- --------------
2.7              56.0%        622,860
3.5              19.3%        214,942
3.6              15.6%        172,974
3.4               8.9%         98,411
3.3               0.1%            789
3.7               0.1%            699
2.6               0.1%            681
3.2               0.0%             19
None              0.0%             13
```

(3.3 also went EOL last month)

**Comment by willkg** [comment]
Sure seems like we can drop support for Python 2.6 now. Less is better. I'll do up a rough PR for it today.

**Comment by hugovk** [comment]
Any thoughts on dropping EOL Python 3.3 as well? Not as big wins to be had compared with dropping 2.6, but it's barely used.

**Comment by willkg** [comment]
@hugovk I don't have an issue for that in the issue tracker, so I haven't been thinking about it. If you want, write up an issue and we can work from there.

**Comment by kevinmarks** [comment]
Dropping support for an old version of python for no good reason and actually changing code to break it on purpose is a hostile act, not good code maintenance.
