### ISSUE TITLE
The serializer sometimes omits the last token

### ISSUE THREAD

**Issue by indivisible** [html5lib/html5lib-python#342]
I've noticed that html5lib.serializer.HTMLSerializer sometimes does not emit the last closing tag for fragments.

[Demonstration of the bug](https://gist.github.com/indivisible/2d4919637e20b235f4c7e9ccf91e595b)

**Comment by cjerdonek** [comment]
I'm guessing this behavior is deliberate. Try this and you'll get a different result:

        serializer = HTMLSerializer(omit_optional_tags=False)

**Comment by indivisible** [comment]
I see, thanks. Although that seems like a terrible default.

**Comment by gsnedders** [comment]
We seem not to have a bug for changing to matching how the spec says to serialise stuff… Oh well, we have https://github.com/html5lib/html5lib-python/issues/344 now.

As @cjerdonek says, this is by design.
