### ISSUE TITLE
Sane version numbering

### ISSUE THREAD

**Issue by emorozov** [html5lib/html5lib-python#346]
Is it possible to switch to sane version numbers? Like sequential numbers, starting from 1.0 or date-based version numbers (like 2017.05).

Current version numbers makes it really hard to understand what version is installed and what version is required. Counting all these nines is not easy.

I understand that for you this is sounds like a cosmetic issue but I constantly find my code broken by html5lib changes and it's hard to figure out which version is broken and to what version I need downgrade to (for example, code that depends on `from html5lib.sanitizer import HTMLSanitizer` is broken.

**Comment by nicktimko** [comment]
https://github.com/html5lib/html5lib-python/issues/282
