### ISSUE TITLE
support uppercase hex characters in css color check

### ISSUE THREAD

**Issue by willkg** [html5lib/html5lib-python#354]
This covers adding support for uppercase hex characters in the css color check regex.

From #287:

> Adds uppercase check (A-F) in the css regex to pass css of the following format:
> border-top: 2px #DA4534 solid;

**Comment by willkg** [comment]
Tossing this in the 1.0 milestone. It might be easy to fix.

The CSS regex check is here:

https://github.com/html5lib/html5lib-python/blob/32713a572324414a8692c8342eaa67f8b6f947d0/html5lib/filters/sanitizer.py#L838

**Comment by hugovk** [comment]
I'll take this.
