### ISSUE TITLE
Drop Python 3.3 support

### ISSUE THREAD

**Issue by hugovk** [html5lib/html5lib-python#357]
Is there any interest in dropping support for EOL Python 3.3?

Here's the pip installs from PyPI for the last month, showing low demand for 3.3:
```
$ pypinfo --percent --pip html5lib pyversion
python_version percent download_count
-------------- ------- --------------
2.7              56.0%        622,860
3.5              19.3%        214,942
3.6              15.6%        172,974
3.4               8.9%         98,411
3.3               0.1%            789
3.7               0.1%            699
2.6               0.1%            681
3.2               0.0%             19
None              0.0%             13
```

* Unsupported since [2017-09-29](https://en.wikipedia.org/wiki/CPython#Version_history)
* pip 10 will deprecate Python 3.3 support, pip 11 won't support it (https://github.com/pypa/pip/issues/3796)
* Very little PyPI traffic (June 2016) https://github.com/pypa/pip/issues/3796

**Comment by willkg** [comment]
Thank you for writing this up with all the relevant links and information--that helps a ton! I'm game for dropping support for Python 3.3. I'll add it to the 1.0 milestone.

If someone has a compelling reason not to drop Python 3.3, please add a comment.

**Comment by gsnedders** [comment]
> If someone has a compelling reason not to drop Python 3.3, please add a comment.

Historically the viewpoint I've taken is given we're vendored into pip we should support the same set of versions as pip does (to avoid any need for pip to fork html5lib).

**Comment by willkg** [comment]
Wow--I had no idea html5lib-python was vendored in pip. That's... interesting.

@gsnedders How do we figure out what versions of pip are supported? Are we just checking their current release to see what versions of Python it supports? For example, master tip still supports Python 3.3:

https://github.com/pypa/pip/blob/3998df351853c68274802502fead7607c8ab8eeb/setup.py#L54

**Comment by hugovk** [comment]
I think it makes sense for pip to vendor things, it needs to be able to install from a download with maybe no external net access except an internal PyPI server.  

Here's the pip decision and PR to deprecate 3.3 in the next pip 10 and drop it in pip 11.
https://github.com/pypa/pip/issues/3796
https://github.com/pypa/pip/pull/4355

Their latest stable docs say 2.6, 2.7, 3.3-3.5, pypy. 
https://pip.pypa.io/en/stable/installing/#python-and-os-compatibility

Latest master says 2.7, 3.3-3.6, pypy. 
https://github.com/pypa/pip/blob/master/docs/installing.rst#python-and-os-compatibility

**Comment by gsnedders** [comment]
@willkg mostly @dstufft pinging me (or me him) when they drop stuff :)

**Comment by willkg** [comment]
That makes sense!

Seems like we shouldn't drop support for 3.3 in html5lib-python 1.0. Beyond that, I'll leave this until you get pinged and we can drop it.
