### ISSUE TITLE
readthedocs isn't tracking master

### ISSUE THREAD

**Issue by willkg** [html5lib/html5lib-python#381]
One of the versions of html5lib-python that readthedocs has is "latest" and it's supposed to track the master branch. Any time we land code, it should rebuild the docs.

It looks like the last time "latest" was rebuilt was 3 weeks ago:

https://readthedocs.org/projects/html5lib/builds/

Is the webhook broken?

This issue covers fixing docs building.

**Comment by willkg** [comment]
@gsnedders Can you either look into this or make me an admin for html5lib-python so I can look into it?

**Comment by gsnedders** [comment]
Hopefully is now.

**Comment by willkg** [comment]
It's definitely up-to-date now. I'll keep an eye on it and reopen this issue if it's not updating.

Thank you!
