### ISSUE TITLE
DeprecationWarning in collections import

### ISSUE THREAD

**Issue by tirkarthi** [html5lib/html5lib-python#402]
Installing html5lib on CPython master generates the below warning. I think this was added as part of Python 3.7 and will be removed in the next version 3.8 which is under development. Just wanted to give a heads up on this.

```
/home/karthi/requests-html-env/lib/python3.8/site-packages/pip/_vendor/html5lib/_trie/_base.py:3: 
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping
```

Relevant code : https://github.com/html5lib/html5lib-python/blob/950ea0ec60970ba1c88bd9e35d8d85c2a1f318e4/html5lib/_trie/_base.py#L3

Possible solution : https://github.com/pyparsing/pyparsing/pull/16

Thanks

**Comment by rzuckerm** [comment]
When is this change going to be released? I'm still seeing this warning.
