### ISSUE TITLE
Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated

### ISSUE THREAD

**Issue by labrys** [html5lib/html5lib-python#405]
It will stop working in Python 3.8.

**Comment by serhiy-storchaka** [comment]
This is a blocker for CPython: https://github.com/python/cpython/pull/10596.

**Comment by labrys** [comment]
@tirkarthi Not a duplicate as the issue still exists.
`from collections import ...` is still used in the following locations:
- `html5lib._tokenizer`
- `html5lib.html5parser`
- `html5lib.filters.alphabeticalattributes`
- `html5lib.tests.test_alphabeticalattributes`
- `html5lib.treewalkers.etree`

**Comment by labrys** [comment]
@tirkarthi you are correct... closing this
