### ISSUE TITLE
Serializer modifies HTML

### ISSUE THREAD

**Issue by davaya** [html5lib/html5lib-python#490]
Parsing and then writing an HTML file results in corruption - some closing elements are missing, and some string attributes are not output as strings.

    import html5lib
    
    file_in = 'divlayout.html'
    file_out = 'divlayout_out.html'
    parser = html5lib.HTMLParser(strict=True, namespaceHTMLElements=False)
    with open(file_in, 'rb') as f:
        doc = parser.parse(f)
    out = html5lib.serializer.serialize(doc)
    print(out)
    with open(file_out, 'w') as f:
        f.write(out)

Using an example HTML file from https://www.tutorialrepublic.com/html-tutorial/html-layout.php, the body portion of the input is:

    </head>
    <body>
        <div class="container">
            <header>
                <h1>Tutorial Republic</h1>
            </header>
            <div class="wrapper clearfix">
                <nav>
                    <ul>
                        <li><a href="#">Home</a></li>
                        <li><a href="#">About</a></li>
                        <li><a href="#">Contact</a></li>
                    </ul>
                </nav>
                <section>
                    <h2>Welcome to our site</h2>
                    <p>Here you will learn how to create websites...</p>
                </section>
            </div>
            <footer>
                <p>copyright &copy; tutorialrepublic.com</p>
            </footer>
        </div>
    </body>
    </html>

But the serialized output is:

    </head>
    <body>
        <div class=container>
            <header>
                <h1>Tutorial Republic</h1>
            </header>
            <div class="wrapper clearfix">
                <nav>
                    <ul>
                        <li><a href=#>Home</a></li>
                        <li><a href=#>About</a></li>
                        <li><a href=#>Contact</a></li>
                    </ul>
                </nav>
                <section>
                    <h2>Welcome to our site</h2>
                    <p>Here you will learn how to create websites...</p>
                </section>
            </div>
            <footer>
                <p>copyright � tutorialrepublic.com</p>
            </footer>
        </div>

Errors:
1. The top class attribute "container" is missing quotes, while in the second class attribute the quotes are correctly preserved. *
2.  The three anchors ("#") are missing quotes.
3.  Most closing tags including `</head>` are preserved, but the closing `</body>` and `</html>` tags are missing. *
4. The HTML entity `&copy;` is converted into a character instead of being preserved as an entity.  This appears to be a parser rather than serializer problem.

Unit tests should include a serializer test comparing input and output HTML files.

* https://stackoverflow.com/questions/6495310/do-you-quote-html5-attributes discusses when quotes *may* be omitted.  But if an author chooses to always include them as recommended, the serializer should not arbitrarily delete them.

* https://blog.teamtreehouse.com/to-close-or-not-to-close-tags-in-html5 describes which tags are optional.  But as above, if an author chooses to include (or not include) optional closing tags, the serializer should not arbitrarily change her choice.
"*Code with closing tags is much more readable and easy to follow. It is much easier to visually inspect a page with well laid out markup. Working with this markup is easier for developers.*"

**Comment by gsnedders** [comment]
The serializer has no knowledge of the input serialization of the tree; it purely operates from the tree, so it's long since lost any information about what attributes are quoted, how much whitespace there is between attributes, what optional tags were omitted, etc.

There are a number of options that affect serialization, among them `quote_attr_values` which affects when attributes get quoted and `omit_optional_tags` which affects whether optional tags get omitted.

I don't know what you expect to happen with entities? `&copy;` parsing to anything but the copyright symbol character would be surprising given that's what it represents. That entities get decoded at parse-time is no different to almost any XML parser. You could use `encoding="ascii"` if you want any non-ASCII character to be represented with an entity, but this again obviously doesn't round-trip.

**Comment by davaya** [comment]
It may be a matter of taste, but lxml is closer to my taste so I'll use that.  It closes tags, and it serializes entities as entities.

lxml does not record all token info in the parse tree, but there is no reason that it could not retain sufficient information to recreate the input exactly, such as different tokens for double quoted, single quoted, and unquoted strings.   Some whitespace is insignificant, but it is already preserved in the tree sufficiently to recreate pretty-printed or squashed inputs that are semantically identical.
