### ISSUE TITLE
Avoid cElementTree on Python 3

### ISSUE THREAD

**Issue by uranusjr** [html5lib/html5lib-python#494]
`cElementTree` has been [deprecated since 3.3](https://docs.python.org/3/library/xml.etree.elementtree.html), and is simply an alias to `ElementTree` right now. It [will be removed in the Python 3.10](https://bugs.python.org/issue36543).

Originally filed as: pypa/pip#8278
See also: python/cpython#19921

**Comment by gsnedders** [comment]
What prompts the desire to avoid it? Avoiding the PendingDeprecationWarning proposed to be added in python/cpython#19921 but not https://github.com/python/cpython/pull/20117? This this causes warnings with the perfectly sane `try/except ImportError` that's so prevalent and future-proof seems ridiculous.

**Comment by uranusjr** [comment]
cc-ing @tiran since I do not have the knowledge to answer the question myself.

**Comment by tiran** [comment]
The removal of cElementTree without a deadline and deprecation warning broke a bunch of packages. I like to re-introduce the module in 3.9 with a warning and remove it in 3.10.

The warning is breaking Python's ensurepip tests. Pip depends on html5lib and html5lib triggers the warning. My patch avoids the warning and keeps the behavior of html5lib. If you want a simpler patch, then just import ``xml.etree.ElementTree`` in all Python versions. This works in Python 2, but it's going to slow down parsing on Python 2 a bit.
