### ISSUE TITLE
html5lib/1.1: 995 failed failed tests

### ISSUE THREAD

**Issue by sandrotosi** [html5lib/html5lib-python#507]
Hello,
in Debian we have a process to run [automated tests](https://salsa.debian.org/python-team/modules/html5lib/-/blob/master/debian/tests/unittests3) and that's currently failing for v1.1: you can look at the logs [here](https://ci.debian.net/data/autopkgtest/testing/amd64/h/html5lib/6324026/log.gz) but just to give you an idea of the amount of failures, the summary is: `995 failed, 23076 passed, 5960 skipped, 1 warnings in 52.11 seconds`

**Comment by gsnedders** [comment]
This is, I think, what would happen if it failed to find the expectations file. I wonder if something, somewhere is looking for it relative to the path of `pytest.ini`? If you copy the `.pytest.expect` file as well, do things start passing?

**Comment by sandrotosi** [comment]
that was exactly it, i was missing to copy also the `.pytest.expect` file; i tested locally and i'm about to upload a fix soon -- thanks!
