### ISSUE TITLE
Move away from Travis CI

### ISSUE THREAD

**Issue by gsnedders** [html5lib/html5lib-python#525]
Probably to GitHub Actions?

While we're rewriting the config, we may well want to migrate to [cibuildwheel](https://pypi.org/project/cibuildwheel/) at the same time, especially before #445 happens (when we'll then need the infra to build non-universal wheels for releases cross-platform).

**Comment by jayaddison** [comment]
GitHub actions is probably the most straightforward alternative at the moment, yep.

Could we build [`universal` wheels](https://wheel.readthedocs.io/en/stable/user_guide.html?highlight=universal#building-wheels)?  I think that'd allow building and publishing wheels without introducing additional build-time dependencies.

Thoughts on build configuration:

During migration, running `tox` is likely the simplest way to run tests under all of the configured [environment combinations](https://github.com/html5lib/html5lib-python/blob/2c19b9899ab3a3e8bd0ca35e5d78544334204169/tox.ini#L2).  That would run all of the tests sequentially in each of the environment configurations and output a single pass/fail indicator in GitHub for the developer.

Perhaps it'd make sense during the migration to have the chosen continuous integration system run each of the configured environments as a separate build (i.e. individual process with pass/fail indicator)?

There are a reasonably large number of environment combinations already (21 by my count?), so we'd want to be careful not to create redundant duplicate work - especially if opening pull requests causes all those workloads to be initiated (resulting in expenditure of compute resources (and therefore energy :)) that it'd be better to conserve).

**Comment by jayaddison** [comment]
Hrm, mapping GHA `strategy.matrix`-based jobs to single `tox` environments looks a little tricky due to the [combinatorial `envlist`](https://github.com/html5lib/html5lib-python/blob/2c19b9899ab3a3e8bd0ca35e5d78544334204169/tox.ini#L2).

**Comment by hugovk** [comment]
GitHub Actions was added in https://github.com/html5lib/html5lib-python/pull/527, and tests are also run on AppVeyor for Windows (this could also be moved to GHA, but that's another issue).

Also Travis CI hasn't been running for 10 months:

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/1324225/161446169-18157d30-d93e-474e-92da-8c46963a3883.png">

https://travis-ci.org/github/html5lib/html5lib-python/builds

Please see https://github.com/html5lib/html5lib-python/pull/545 to remove Travis CI config and replace with GHA in docs.
