### ISSUE TITLE
ModuleNotFoundError: No module named 'xml'

### ISSUE THREAD

**Issue by alassaneg** [html5lib/html5lib-python#540]
Hello,

I've been trying to execute a code using html5lib but i'm having the following error:

`  File "/usr/lib/python3.9/site-packages/html5lib/_utils.py", line 13, in <module>
    import xml.etree.ElementTree as default_etree
ModuleNotFoundError: No module named 'xml'
`
I'm using python 3.9 .
Is that a known issue on your side?

Thanks in advance for your reply

**Comment by sujaldev** [comment]
Could you show the entire traceback?

**Comment by ambv** [comment]
Cannot reproduce. Inability to import a standard library module is most likely an end-user environment problem or a corrupt Python installation.
