### ISSUE TITLE
use unittest.mock instead of mock

### ISSUE THREAD

**Issue by pgajdos** [html5lib/html5lib-python#541]
Could you please consider to use unittest.mock at least as fallback, when mock is not installed?

**Comment by hugovk** [comment]
Please see PR https://github.com/html5lib/html5lib-python/pull/536 that drops support for EOL Python and replaces the mock library with the stdlib.

**Comment by pgajdos** [comment]
Thanks!

**Comment by eli-schwartz** [comment]
Interesting that this ticket was closed without a PR merged to implement it. :)
