### ISSUE TITLE
On html5lib maintenance

### ISSUE THREAD

**Issue by akx** [html5lib/html5lib-python#555]
Hi there!

https://github.com/html5lib/html5lib-python/issues/361 discusses funding for maintenance, but that conversation has languished a year and a half ago.

It looks like there's a bunch of PRs that would bring this repo a bit into the present (and into the future!), but there's... maybe no one around to merge them? Sorry for the ping, but @gsnedders, @jgraham, you seem to have been the last folks to merge PRs around here; would you need a hand maintaining things and getting things rolling again?

For clarity, my angle here is that I inadvertently caused a bit of havoc over at nbconvert by switching their HTML sanitization away from `lxml.clean_html` to `bleach`, which, as we know, uses `html5lib` under the hood, and there are some performance issues now; see https://github.com/jupyter/nbconvert/issues/1892. Also, for the record, I'm no stranger to maintaining a popular PyPI package; I'm the current de facto maintainer of [babel](https://pypi.org/project/Babel/).

**Comment by rix1337** [comment]
If this repo is abandoned, maybe you maintaining a similarly named fork would work?

`html5lib_next` or sth similar?

**Comment by akx** [comment]
Guess not :) Closing this issue to clean up my GH issues list.

**Comment by claudep** [comment]
And it's a shame! While everyone can understand that maintainers may get out of time for some projects or simply get burned out, it's a lot more difficult to understand ignorance of help requests by recognized Python developers. Please…

@akx, forking would be an alternative here.
