### ISSUE TITLE
ImportError: Can't determine version for html5lib

### ISSUE THREAD

**Issue by mikeyenmoris** [html5lib/html5lib-python#556]
Hi
I wonder if you could help with this problem: I am using pandas to read and process some web data. Until I updated all my python libraries recently, everything worked fine, but I am now receiving the error above. I appear to have html5lib version 0.9999999 now, but I am unsure what the previous version is. Pandas uses the read_html function to collect tables from the webpage. The complete Traceback of the Error is given below.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[2], line 5
      1 # First collect the current records for each distance at the track
      2 # We need a dictionary of track record times
      4 RECORDS_URL = 'http://www.mauritiusturfclub.com/index.php/en/racing/track-records'
----> 5 records = pd.read_html(RECORDS_URL)
      7 for index, row in records[0].iterrows():
      8     dist = float(row['Distance'].strip('m'))

File ~/opt/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py:311, in deprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    305 if len(args) > num_allow_args:
    306     warnings.warn(
    307         msg.format(arguments=arguments),
    308         FutureWarning,
    309         stacklevel=stacklevel,
    310     )
--> 311 return func(*args, **kwargs)

File ~/opt/anaconda3/lib/python3.9/site-packages/pandas/io/html.py:1100, in read_html(io, match, flavor, header, index_col, skiprows, attrs, parse_dates, thousands, encoding, decimal, converters, na_values, keep_default_na, displayed_only)
    950 @deprecate_nonkeyword_arguments(version="2.0")
    951 def read_html(
    952     io: FilePath | ReadBuffer[str],
   (...)
    966     displayed_only: bool = True,
    967 ) -> list[DataFrame]:
    968     r"""
    969     Read HTML tables into a ``list`` of ``DataFrame`` objects.
    970 
   (...)
   1098     <io.read_html>` for some examples of reading in HTML tables.
   1099     """
-> 1100     _importers()
   1102     # Type check here. We don't want to parse only to fail because of an
   1103     # invalid value of an integer skiprows.
   1104     if isinstance(skiprows, numbers.Integral) and skiprows < 0:

File ~/opt/anaconda3/lib/python3.9/site-packages/pandas/io/html.py:66, in _importers()
     63 lxml = import_optional_dependency("lxml.etree", errors="ignore")
     64 _HAS_LXML = lxml is not None
---> 66 html5lib = import_optional_dependency("html5lib", errors="ignore")
     67 _HAS_HTML5LIB = html5lib is not None
     69 _IMPORTS = True

File ~/opt/anaconda3/lib/python3.9/site-packages/pandas/compat/_optional.py:154, in import_optional_dependency(name, extra, errors, min_version)
    152 minimum_version = min_version if min_version is not None else VERSIONS.get(parent)
    153 if minimum_version:
--> 154     version = get_version(module_to_get)
    155     if version and Version(version) < Version(minimum_version):
    156         msg = (
    157             f"Pandas requires version '{minimum_version}' or newer of '{parent}' "
    158             f"(version '{version}' currently installed)."
    159         )

File ~/opt/anaconda3/lib/python3.9/site-packages/pandas/compat/_optional.py:80, in get_version(module)
     76     if module.__name__ == "snappy":
     77         # snappy doesn't contain attributes to confirm it's version
     78         # See https://github.com/andrix/python-snappy/pull/119
     79         return ""
---> 80     raise ImportError(f"Can't determine version for {module.__name__}")
     81 if module.__name__ == "psycopg2":
     82     # psycopg2 appends " (dt dec pq3 ext lo64)" to it's version
     83     version = version.split()[0]

ImportError: Can't determine version for html5lib

Thanks

Michael Parry

**Comment by ambv** [comment]
I cannot reproduce this. I'm doing this:

```
$ conda activate base
$ conda clean --all
$ conda install anaconda==2022.10

$ conda create -n html5lib-test python=3.9
$ conda activate html5lib-test
$ conda install html5lib pandas
```

Then I just launch `python` and do:

```
>>> RECORDS_URL='http://www.mauritiusturfclub.com/index.php/en/racing/track-records'
>>> import pandas as pd
>>> pd.read_html(RECORDS_URL)
[    Year Distance             Horse     Time
0   2017     950m              Emie  0m53.54
1   2020     990m      Emerald Band  0m54.58
2   2014    1000m           Twitter  0m55.94
3   2013    1365m     Captain's Key  1m20.66
4   2011    1400m      Green Keeper  1m22.21
5   2020    1450m         Marauding  1m26.85
6   2013    1500m  Tales of Bravery  1m28.87
7   2010    1600m       Disa Leader  1m34.46
8   2010    1650m       Disa Leader  1m39.78
9   2013    1850m            Vettel  1m51.50
10  2009    2050m      Solar Symbol  2m05.93
11  2012    2100m  Intercontinental  2m08.00
12  2014    2200m     Diamond Light  2m14.09
13  2013    2400m  Intercontinental  2m26.85]
>>> 'html5lib' in sys.modules  # did Pandas import html5lib? yes:
True
>>> import html5lib
>>> html5lib.__version__
'1.1'
```

For your convenience, that's the output of `conda list` for this environment:
```
blas                      1.0                    openblas
bottleneck                1.3.5            py39heec5a64_0
ca-certificates           2023.01.10           hca03da5_0
certifi                   2022.12.7        py39hca03da5_0
html5lib                  1.1                pyhd3eb1b0_0
icu                       68.1                 hc377ac9_0
libcxx                    14.0.6               h848a8c0_0
libffi                    3.4.2                hca03da5_6
libgfortran               5.0.0           11_3_0_hca03da5_28
libgfortran5              11.3.0              h009349e_28
libiconv                  1.16                 h1a28f6b_2
libopenblas               0.3.21               h269037a_0
libxml2                   2.9.14               h8c5e841_0
libxslt                   1.1.35               h9833966_0
llvm-openmp               14.0.6               hc6e5704_0
lxml                      4.9.1            py39h2fae87d_0
ncurses                   6.4                  h313beb8_0
numexpr                   2.8.4            py39h79ee842_0
numpy                     1.23.5           py39h1398885_0
numpy-base                1.23.5           py39h90707a3_0
openssl                   1.1.1t               h1a28f6b_0
packaging                 22.0             py39hca03da5_0
pandas                    1.5.2            py39h78102c4_0
pip                       22.3.1           py39hca03da5_0
python                    3.9.16               hc0d8a6c_0
python-dateutil           2.8.2              pyhd3eb1b0_0
pytz                      2022.7           py39hca03da5_0
readline                  8.2                  h1a28f6b_0
setuptools                65.6.3           py39hca03da5_0
six                       1.16.0             pyhd3eb1b0_1
sqlite                    3.40.1               h7a7dc30_0
tk                        8.6.12               hb8d0fd4_0
tzdata                    2022g                h04d1e81_0
webencodings              0.5.1            py39hca03da5_1
wheel                     0.38.4           py39hca03da5_0
xz                        5.2.10               h80987f9_1
zlib                      1.2.13               h5a0b063_0
```

I suggest you check how to clean your Anaconda environment but this isn't a bug in html5lib.
