### ISSUE TITLE
Link rot: Both links under "Questions?" are invalid

### ISSUE THREAD

**Issue by Avasam** [html5lib/html5lib-python#578]
Hi, just wanna say that http://groups.google.com/group/html5lib-discuss leads nowhere and that http://wiki.whatwg.org/wiki/IRC leads to a redirection page.

**Comment by ambv** [comment]
You mean on PyPI? Yes, that's an old release. As you can see, the README here is updated.

**Comment by Avasam** [comment]
Oh my bad, I searched for similar issues, but didn't think to check against master.
